version: '3.8'

services:
  dbt-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    volumes:
      - ./pk:/app/pk
      - ./frontend:/app/frontend
      - ./backend:/app/backend
    environment:
      - DBT_PROJECTS_DIR=/app/pk
      - API_HOST=0.0.0.0
      - API_PORT=8085
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - dbt-network

networks:
  dbt-network:
    driver: bridge 