name: 'finance'
version: '1.0.0'
config-version: 2

profile: 'finance'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  finance:
    staging:
      +materialized: view
    core:
      +materialized: table 