# Global default settings
default:
  target: dev
  outputs:
    dev:
      type: sqlite
      database: /Users/telvin/Desktop/dbt/dbt_projects_2/insurance_data.db
      schema: main
      threads: 1

# Claims Processing project profile
claims_processing:
  target: dev
  outputs:
    dev:
      type: sqlite
      database: /Users/telvin/Desktop/dbt/dbt_projects_2/insurance_data.db
      schema: main
      threads: 1

# Policy Management project profile
policy_management:
  target: dev
  outputs:
    dev:
      type: sqlite
      database: /Users/telvin/Desktop/dbt/dbt_projects_2/insurance_data.db
      schema: main
      threads: 1

# Customer Risk project profile
customer_risk:
  target: dev
  outputs:
    dev:
      type: sqlite
      database: /Users/telvin/Desktop/dbt/dbt_projects_2/insurance_data.db
      schema: main
      threads: 1

# You can also define production environments if needed
# claims_processing:
#   outputs:
#     prod:
#       type: sqlite
#       database: /path/to/production/insurance_data.db
#       schema: main
#       threads: 4 