# Global default settings
insurance_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /Users/telvin/Desktop/dbt/dbt_projects_2/insurance_data.db
      schema: main

# Claims Processing project profile
claims_processing:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /Users/telvin/Desktop/dbt/dbt_projects_2/insurance_data.db
      schema: main

# Policy Management project profile
policy_management:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /Users/telvin/Desktop/dbt/dbt_projects_2/insurance_data.db
      schema: main

# Customer Risk project profile
customer_risk:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /Users/telvin/Desktop/dbt/dbt_projects_2/insurance_data.db
      schema: main

# You can also define production environments if needed
# retail_ops:
#   target: dev
#   outputs:
#     dev:
#       type: duckdb
#       path: /Users/telvin/Desktop/dbt/dbt_projects/data/retail_warehouse.duckdb
#       schema: retail

# customer_360:
#   target: dev
#   outputs:
#     dev:
#       type: duckdb
#       path: /Users/telvin/Desktop/dbt/dbt_projects/data/retail_warehouse.duckdb
#       schema: customer

# finance_metrics:
#   target: dev
#   outputs:
#     dev:
#       type: duckdb
#       path: /Users/telvin/Desktop/dbt/dbt_projects/data/retail_warehouse.duckdb
#       schema: finance 