name: 'marketing'
version: '1.0.0'
config-version: 2

profile: 'marketing'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  marketing:
    staging:
      +materialized: view
    reporting:
      +materialized: table 