name: 'customer_project'
version: '1.0.0'
config-version: 2

profile: 'customer_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]
asset-paths: ["assets"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  customer_project:
    # Config defaults for all models in the project
    +materialized: view
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: marts

# On-run-end hook to inform about cross-project dependencies
on-run-end:
  - "{{ log('Customer project run complete. This project is referenced by both policy_project and claims_project.', info=True) }}" 