version: 2

seeds:
  - name: raw_policies
    description: "Sample policy data for testing"
    config:
      schema: raw_insurance
      column_types:
        policy_id: integer
        customer_id: integer
        premium_amount: float
        coverage_limit: float
        deductible_amount: float
        effective_date: date
        expiration_date: date
        created_at: timestamp
        updated_at: timestamp
    columns:
      - name: policy_id
        description: "Unique identifier for the policy"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "ID of the customer who owns the policy"
        tests:
          - not_null
          - relationships:
              to: ref('raw_customers', 'customer_project')
              field: customer_id
      - name: policy_type
        description: "Type of insurance policy (auto, home, life, health)"
      - name: policy_number
        description: "Policy number for identification"
        tests:
          - unique
      - name: premium_amount
        description: "Annual premium amount for the policy"
      - name: coverage_limit
        description: "Maximum coverage amount"
      - name: deductible_amount
        description: "Deductible amount for claims"
      - name: effective_date
        description: "Date when the policy becomes effective"
      - name: expiration_date
        description: "Date when the policy expires"
      - name: status
        description: "Current status of the policy"
      - name: created_at
        description: "Timestamp when the record was created"
      - name: updated_at
        description: "Timestamp when the record was last updated"